#encoding: UTF-8
title: 포트폴리오
#author: Seung-Hyun Lee
email: szhyun2002@gmail.com
inhabit: Seoul, Korea
blog: https://shxrecord.tistory.com
github: https://github.com/eeesnghyun
description: > # this means to ignore newlines until "show_exerpts:"
  백엔드 개발자 이승현입니다.
show_excerpts: false # set to true to show excerpts on the homepage
#baseurl: "/gitweb-test"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: 이승현
  tagline:
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: About
      url: "about"
    - title: Works
      url: "works"
    - title: Interview
      url: "interview"
  #search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "ko" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  post_label: 개발과정
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    #twitter: samarsault
    #github:  eeesnghyun
    #linkedIn: in/samarsault
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: szhyun2002@gmail.com

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jemoji
#  - jekyll-feed

